- name: Deploy NextJS
  hosts: frontend
  become: yes

  tasks:
    - name: Install Required Packages
      ansible.builtin.apt:
        name:
          - acl

        state: present

    - name: Install nodejs
      ansible.builtin.shell:
        cmd: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
          NODE_MAJOR=18
          echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
          sudo apt-get update
          sudo apt-get install nodejs -y

    - name: Install pm2
      ansible.builtin.shell:
        cmd: |
          sudo npm install pm2 -g

    - name: Create system user
      ansible.builtin.user:
        name: nextjs
        shell: /usr/sbin/nologin
        state: present # Check if user exists
        system: yes

    - name: Clone repository to local
      become_user: nextjs
      ansible.builtin.git:
        repo: "https://{{ ansible_env.PAT }}@github.com/{{ ansible_env.REPOSITORY }}"
        dest: /home/nextjs/frontendapplication
        single_branch: yes
        version: main

    - name: Copy client cert into remote machine
      ansible.builtin.copy:
        src: "certs/client.crt"
        dest: "/home/nextjs/frontendapplication/client.crt"
        owner: nextjs
        group: nextjs
        mode: 0600

    - name: Copy client key into remote machine
      ansible.builtin.copy:
        src: "certs/client.key"
        dest: "/home/nextjs/frontendapplication/client.key"
        owner: nextjs
        group: nextjs
        mode: 0600

    - name: Start NextJS frontend
      become_user: nextjs
      args:
        chdir: "/home/nextjs/frontendapplication"
      ansible.builtin.shell:
        cmd: |
          npm install
          npm run build
          pm2 start npm --name frontend -- run start -- -p 3000
